<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Client Custom Flexipage</comment>
        <content>BankingPersonAccountPage1</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Account</pageOrSobjectType>
    </actionOverrides>
    <brand>
        <headerColor>#0070D2</headerColor>
        <logoVersion>1</logoVersion>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <description>The platform for retail banking collaboration and productivity</description>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <label>Retail Banking</label>
    <navType>Standard</navType>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>WT Business Administrator</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>WT Case Only</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>WT CCPA</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>WT Compliance</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>WT Contact Center</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>WT Deposit Applications</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>WT Mortgage</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>WT MyHR</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>WT Read Only</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>WT Referral</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>WT Retail</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>WT Sales</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>WT Technical Administrator</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>WT_Event_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Event</pageOrSobjectType>
        <recordType>Event.WT_Event</recordType>
        <type>Flexipage</type>
        <profile>WT Wealth</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>WT Business Administrator</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>WT Case Only</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>WT CCPA</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>WT Compliance</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>WT Contact Center</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>WT Deposit Applications</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>WT Mortgage</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>WT MyHR</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>WT Read Only</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>WT Referral</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>WT Retail</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>WT Sales</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>WT Technical Administrator</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_CCPA</recordType>
        <type>Flexipage</type>
        <profile>WT Wealth</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>WT Business Administrator</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>WT Case Only</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>WT CCPA</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>WT Compliance</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>WT Contact Center</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>WT Deposit Applications</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>WT Mortgage</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>WT MyHR</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>WT Read Only</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>WT Referral</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>WT Retail</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>WT Sales</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>WT Technical Administrator</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Compliance_Complaint</recordType>
        <type>Flexipage</type>
        <profile>WT Wealth</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>WT Business Administrator</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>WT Case Only</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>WT CCPA</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>WT Compliance</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>WT Contact Center</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>WT Deposit Applications</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>WT Mortgage</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>WT MyHR</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>WT Read Only</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>WT Referral</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>WT Retail</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>WT Sales</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>WT Technical Administrator</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Case_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <recordType>Case.WT_Deposit_Application</recordType>
        <type>Flexipage</type>
        <profile>WT Wealth</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>WT_Mortgage_Home_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>WT Mortgage</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>WT_Wealth_Home_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>WT Wealth</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>WT_Retail_Home_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>WT Retail</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>FinServ__WealthHome</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>FinServ__WealthHome</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Advisor</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>FinServ__BankingHomePage</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Personal Banker</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>FinServ__BankingBusinessAccountPage</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.FinServ__IndustriesBusiness</recordType>
        <type>Flexipage</type>
        <profile>Advisor</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>FinServ__BankingBusinessAccountPage</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.FinServ__IndustriesBusiness</recordType>
        <type>Flexipage</type>
        <profile>Personal Banker</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>FinServ__BankingBusinessAccountPage</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.FinServ__IndustriesBusiness</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>FinServ__BankingBusinessContactPage</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.FinServ__IndustriesBusiness</recordType>
        <type>Flexipage</type>
        <profile>Advisor</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>FinServ__BankingBusinessContactPage</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.FinServ__IndustriesBusiness</recordType>
        <type>Flexipage</type>
        <profile>Personal Banker</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>FinServ__BankingBusinessContactPage</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.FinServ__IndustriesBusiness</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>FinServ__BankingHouseholdPageTwoColumn</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.FinServ__IndustriesHousehold</recordType>
        <type>Flexipage</type>
        <profile>Advisor</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>FinServ__BankingHouseholdPageTwoColumn</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.FinServ__IndustriesHousehold</recordType>
        <type>Flexipage</type>
        <profile>Personal Banker</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>FinServ__BankingIndividualPageTwoColumn</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.FinServ__IndustriesIndividual</recordType>
        <type>Flexipage</type>
        <profile>Advisor</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>FinServ__BankingIndividualPageTwoColumn</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.FinServ__IndustriesIndividual</recordType>
        <type>Flexipage</type>
        <profile>Personal Banker</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>FinServ__BankingIndividualPageTwoColumn</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.FinServ__IndustriesIndividual</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>FinServ__BankingHouseholdPageTwoColumn</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>Account.FinServ__IndustriesHousehold</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <subscriberTabs>standard-Case</subscriberTabs>
    <subscriberTabs>CTI_Contact_Search</subscriberTabs>
    <subscriberTabs>Contact_Center_Favorites</subscriberTabs>
    <subscriberTabs>WT_SharePoint</subscriberTabs>
    <tabs>standard-home</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>FinServ__FinancialAccount__c</tabs>
    <tabs>FinServ__AssetsAndLiabilities__c</tabs>
    <tabs>FinServ__FinancialGoal__c</tabs>
    <tabs>FinServ__ReciprocalRole__c</tabs>
    <tabs>standard-Lead</tabs>
    <tabs>standard-Opportunity</tabs>
    <tabs>standard-report</tabs>
    <tabs>standard-Dashboard</tabs>
    <uiType>Lightning</uiType>
</CustomApplication>
