<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <label>Business Rules Engine</label>
    <navType>Console</navType>
    <tabs>standard-CalculationProcedure</tabs>
    <tabs>standard-CalculationMatrix</tabs>
    <tabs>standard-DecisionTable</tabs>
    <tabs>standard-ExpressionSetTemplate</tabs>
    <tabs>standard-ExpressionSet</tabs>
    <tabs>WT_Knowledge_Search_Log__c</tabs>
    <tabs>WT_Knowledge_Vote__c</tabs>
    <tabs>tffa__AddOnServiceItem__c</tabs>
    <tabs>WT_CI_Funding_History__c</tabs>
    <tabs>WT_Opportunity_Stage_Tracking__c</tabs>
    <uiType>Lightning</uiType>
    <workspaceConfig>
        <mappings>
            <tab>WT_CI_Funding_History__c</tab>
        </mappings>
        <mappings>
            <tab>WT_Knowledge_Search_Log__c</tab>
        </mappings>
        <mappings>
            <tab>WT_Knowledge_Vote__c</tab>
        </mappings>
        <mappings>
            <tab>WT_Opportunity_Stage_Tracking__c</tab>
        </mappings>
        <mappings>
            <tab>standard-CalculationMatrix</tab>
        </mappings>
        <mappings>
            <tab>standard-CalculationProcedure</tab>
        </mappings>
        <mappings>
            <tab>standard-DecisionTable</tab>
        </mappings>
        <mappings>
            <tab>standard-ExpressionSet</tab>
        </mappings>
        <mappings>
            <tab>standard-ExpressionSetTemplate</tab>
        </mappings>
        <mappings>
            <tab>tffa__AddOnServiceItem__c</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
