<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <label>Salesforce CMS</label>
    <navType>Console</navType>
    <tabs>standard-CmsAuthorHome</tabs>
    <tabs>standard-CmsChannel</tabs>
    <tabs>standard-CmsWorkspaces</tabs>
    <tabs>standard-CmsExperiences</tabs>
    <tabs>WT_Third_Party_Data__c</tabs>
    <tabs>WT_Knowledge_Search_Log__c</tabs>
    <tabs>WT_Knowledge_Vote__c</tabs>
    <tabs>tffa__AddOnServiceItem__c</tabs>
    <tabs>WT_CI_Funding_History__c</tabs>
    <tabs>WT_Opportunity_Stage_Tracking__c</tabs>
    <uiType>Lightning</uiType>
    <workspaceConfig>
        <mappings>
            <tab>WT_CI_Funding_History__c</tab>
        </mappings>
        <mappings>
            <tab>WT_Knowledge_Search_Log__c</tab>
        </mappings>
        <mappings>
            <tab>WT_Knowledge_Vote__c</tab>
        </mappings>
        <mappings>
            <tab>WT_Opportunity_Stage_Tracking__c</tab>
        </mappings>
        <mappings>
            <tab>WT_Third_Party_Data__c</tab>
        </mappings>
        <mappings>
            <tab>standard-CmsAuthorHome</tab>
        </mappings>
        <mappings>
            <tab>standard-CmsChannel</tab>
        </mappings>
        <mappings>
            <tab>standard-CmsExperiences</tab>
        </mappings>
        <mappings>
            <tab>standard-CmsWorkspaces</tab>
        </mappings>
        <mappings>
            <tab>tffa__AddOnServiceItem__c</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
