<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <label>Insurance Agent Console</label>
    <navType>Console</navType>
    <tabs>standard-home</tabs>
    <tabs>standard-InsurancePolicy</tabs>
    <tabs>standard-Claim</tabs>
    <tabs>standard-CustomerProperty</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-Lead</tabs>
    <tabs>standard-Opportunity</tabs>
    <tabs>standard-Case</tabs>
    <tabs>standard-report</tabs>
    <tabs>standard-Dashboard</tabs>
    <tabs>WT_Third_Party_Data__c</tabs>
    <tabs>WT_Knowledge_Search_Log__c</tabs>
    <tabs>WT_Knowledge_Vote__c</tabs>
    <tabs>tffa__AddOnServiceItem__c</tabs>
    <tabs>WT_CI_Funding_History__c</tabs>
    <tabs>WT_Opportunity_Stage_Tracking__c</tabs>
    <uiType>Lightning</uiType>
    <workspaceConfig>
        <mappings>
            <tab>WT_CI_Funding_History__c</tab>
        </mappings>
        <mappings>
            <tab>WT_Knowledge_Search_Log__c</tab>
        </mappings>
        <mappings>
            <tab>WT_Knowledge_Vote__c</tab>
        </mappings>
        <mappings>
            <tab>WT_Opportunity_Stage_Tracking__c</tab>
        </mappings>
        <mappings>
            <tab>WT_Third_Party_Data__c</tab>
        </mappings>
        <mappings>
            <tab>standard-Account</tab>
        </mappings>
        <mappings>
            <tab>standard-Case</tab>
        </mappings>
        <mappings>
            <tab>standard-Claim</tab>
        </mappings>
        <mappings>
            <tab>standard-CustomerProperty</tab>
        </mappings>
        <mappings>
            <tab>standard-Dashboard</tab>
        </mappings>
        <mappings>
            <tab>standard-InsurancePolicy</tab>
        </mappings>
        <mappings>
            <tab>standard-Lead</tab>
        </mappings>
        <mappings>
            <tab>standard-Opportunity</tab>
        </mappings>
        <mappings>
            <tab>standard-home</tab>
        </mappings>
        <mappings>
            <tab>standard-report</tab>
        </mappings>
        <mappings>
            <tab>tffa__AddOnServiceItem__c</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
