<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>Tab</actionName>
        <content>tffa__OperationsHome</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>Tab</actionName>
        <content>tffa__OperationsHome</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
    </actionOverrides>
    <brand>
        <headerColor>#0070D2</headerColor>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <description>Manage your operations like sales, service with submissions, parties, applications, and more</description>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <label>Terafina Operations</label>
    <navType>Console</navType>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>OperationsHome</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <tabs>standard-home</tabs>
    <tabs>tffa__Search</tabs>
    <tabs>tffa__Submission__c</tabs>
    <tabs>tffa__Application__c</tabs>
    <tabs>tffa__Party__c</tabs>
    <tabs>standard-Dashboard</tabs>
    <tabs>standard-report</tabs>
    <tabs>tffa__Recommendation__c</tabs>
    <tabs>tffa__FinancialNeed__c</tabs>
    <tabs>tffa__Referral_Home</tabs>
    <tabs>tffa__Referral__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>tffa__TfOperations_UtilityBar</utilityBar>
    <workspaceConfig>
        <mappings>
            <tab>standard-Dashboard</tab>
        </mappings>
        <mappings>
            <tab>standard-home</tab>
        </mappings>
        <mappings>
            <tab>standard-report</tab>
        </mappings>
        <mappings>
            <tab>tffa__Application__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__FinancialNeed__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__Party__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__Recommendation__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__Referral_Home</tab>
        </mappings>
        <mappings>
            <tab>tffa__Referral__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__Search</tab>
        </mappings>
        <mappings>
            <tab>tffa__Submission__c</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
