<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>Tab</actionName>
        <content>tffa__BusinessConfigurationHome</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
    </actionOverrides>
    <brand>
        <headerColor>#0070D2</headerColor>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <description>Manage your Business configurations for running your Sales processes</description>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>true</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <label>Terafina Business Configuration</label>
    <navType>Console</navType>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>OperationsHome1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>TerafinaBranchManager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>OperationsHome1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>TerafinaBranchUser</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>OperationsHome1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>TerafinaContactCenter</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>OperationsHome1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>TerafinaRegionalManager</profile>
    </profileActionOverrides>
    <tabs>standard-home</tabs>
    <tabs>tffa__Product__c</tabs>
    <tabs>tffa__AddOnService__c</tabs>
    <tabs>tffa__AddOnServiceChecklist__c</tabs>
    <tabs>tffa__AddOnServiceMatrix__c</tabs>
    <tabs>tffa__AgentDetail__c</tabs>
    <tabs>tffa__AllowedAddress__c</tabs>
    <tabs>tffa__ApplicantRole__c</tabs>
    <tabs>tffa__ApplicantRoleMatrix__c</tabs>
    <tabs>tffa__ApplicationDecisionMatrix__c</tabs>
    <tabs>tffa__ApplicationRoutingMatrix__c</tabs>
    <tabs>tffa__ApplicationScoringMatrix__c</tabs>
    <tabs>tffa__Brand__c</tabs>
    <tabs>tffa__CollateralArrangementConfiguration__c</tabs>
    <tabs>tffa__CollateralArrangementConfigurationMatrix__c</tabs>
    <tabs>tffa__DecisionStrategyConfiguration__c</tabs>
    <tabs>tffa__DepositBoxConfiguration__c</tabs>
    <tabs>tffa__DisclosureChecklist__c</tabs>
    <tabs>tffa__DisclosureTemplate__c</tabs>
    <tabs>tffa__DisclosureMatrix__c</tabs>
    <tabs>tffa__EducationalInstitutionSpecification__c</tabs>
    <tabs>tffa__FundingMatrix__c</tabs>
    <tabs>tffa__ListOfValues__c</tabs>
    <tabs>tffa__Location__c</tabs>
    <tabs>tffa__LookupTable__c</tabs>
    <tabs>tffa__Offer__c</tabs>
    <tabs>tffa__OfferMatrix__c</tabs>
    <tabs>tffa__PartyAgeMatrix__c</tabs>
    <tabs>tffa__PartyDecisionMatrix__c</tabs>
    <tabs>tffa__PartyRelationCode__c</tabs>
    <tabs>tffa__ProductMatrix__c</tabs>
    <tabs>tffa__Promotion__c</tabs>
    <tabs>tffa__Questionnaire__c</tabs>
    <tabs>tffa__QuestionnaireMatrix__c</tabs>
    <tabs>tffa__RecommendationConfiguration__c</tabs>
    <tabs>tffa__ReferralProgram__c</tabs>
    <tabs>tffa__ReferralProgramMatrix__c</tabs>
    <tabs>tffa__StipulationChecklist__c</tabs>
    <tabs>tffa__StipulationTemplate__c</tabs>
    <tabs>tffa__StipulationMatrix__c</tabs>
    <tabs>tffa__UXStrategy__c</tabs>
    <tabs>tffa__ValueConfiguration__c</tabs>
    <tabs>tffa__VehicleSpecification__c</tabs>
    <tabs>standard-File</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>tffa__TfConfiguration_UtilityBar</utilityBar>
    <workspaceConfig>
        <mappings>
            <tab>standard-File</tab>
        </mappings>
        <mappings>
            <tab>standard-home</tab>
        </mappings>
        <mappings>
            <tab>tffa__AddOnServiceChecklist__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__AddOnServiceMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__AddOnService__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__AgentDetail__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__AllowedAddress__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__ApplicantRoleMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__ApplicantRole__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__ApplicationDecisionMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__ApplicationRoutingMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__ApplicationScoringMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__Brand__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__CollateralArrangementConfigurationMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__CollateralArrangementConfiguration__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__DecisionStrategyConfiguration__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__DepositBoxConfiguration__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__DisclosureChecklist__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__DisclosureMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__DisclosureTemplate__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__EducationalInstitutionSpecification__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__FundingMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__ListOfValues__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__Location__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__LookupTable__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__OfferMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__Offer__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__PartyAgeMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__PartyDecisionMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__PartyRelationCode__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__ProductMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__Product__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__Promotion__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__QuestionnaireMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__Questionnaire__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__RecommendationConfiguration__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__ReferralProgramMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__ReferralProgram__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__StipulationChecklist__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__StipulationMatrix__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__StipulationTemplate__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__UXStrategy__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__ValueConfiguration__c</tab>
        </mappings>
        <mappings>
            <tab>tffa__VehicleSpecification__c</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
