public with sharing class FISCCCreateNewDepositAccDTO {
  public FISCCCreateNewDepositAccDTO() {
  }
  public String DPAcctNbrNewAcct;
  //public String AcctNbr;
  public Integer DPBrnch;
  public Integer DPAcctTyp;
  public String DPAcctNme;
  public String DPFedWithholdingInd;
  public String DPFedTaxId;
  public String DPFedTaxNbr;
  public Integer DPCstCntr;
  public String DPTrckCde;
  public Integer DPPrmyOffcr;
  public Integer DPIntPln;
  public String DPDPCat;
  public Long DPNmeAndAddrBusPh;
  public Long DPNmeAndAddrHmPh;
  public String DPStatCodes;
  public String CINmeAddrLne01;
  public Integer DPFundsAEP;
  public String RmrkExpDte;
  public String RmrkLne01;
  public String CIRmrkMaintSrcInd;
  public Date DPBirthdate;
  public Integer DPExcpPlnNbr;
}