public with sharing class FISCCDebitCardAccRelRequestDTO {
    public String CIRltApplNbr01;
    public String CIEnt1ToEnt2RltCde;
    public String PriSecRltCde01;
    public String CINmeAddrLneCde01;
    public String CINmeAddrLneCde02;
    public String CINmeAddrLneCde03;
    public String CINmeAddrLneCde04;
    public String NmeAddrLne01;
    public String NmeAddrLne02;
    public String NmeAddrLne03;
    public String NmeAddrLne04;
    public String ApplCde;
    public String AcctNbr;
    public String RmrkLne01;
    public String NAStandardizationOvride;
}