public with sharing class FISCCDepositNameAddressDTO {
  public FISCCDepositNameAddressDTO() {
  }
  public String DPAcctNbrNmeAddrMaint;
  public String DPCIRqstInd;
  public Long DPNmeAndAddrHmPh;
  public Long DPNmeAndAddrBusPh;
  public Integer DPNmeAndAddrTyp;
  public String DPNmeAndAddrLne1;
  public String DPNmeAndAddrLne2;
  public String DPNmeAndAddrLne3;
  public String DPNmeAndAddrLne4;
  public String DPNmeAndAddrLne5;
  public String DPNmeAndAddrLne6;
  public String DPNmeAndAddrLne7;
  public String DPNmeAndAddrLne8;
}