public with sharing class FISCCDODueDiligenceDTO {
  public FISCCDODueDiligenceDTO() {
  }
  public String CustNbr;
  public String InitDp;
  public String TypOfFunds;
  public String SrcOfFunds;
  public String NbrOfDp;
  public String TotDpAmt;
  public String NbrCashDp;
  public String CashDpAmt;
  public String NbrOfCashWthdrwl;
  public String CashWthdrwlAmt;
  public String NbrOfChkWritn;
  public String CkAmtWritn;
  public String AntWireAct;
  public String DomInWireAct;
  public String NbrDomWire;
  public String DomInWireAmt;
  public String DomOutWireAct;
  public String NbrDomOutWire;
  public String DomOutWireAmt;
  public String FrgnInWireAct;
  public String NbrFrgnInWire;
  public String FrgnInWireAmt;
  public String FrgnOutWireAct;
  public String NbrFrgnOutWire;
  public String FrgnOutWireAmt;
  public String PolExpsedOrg;
  public String PolRel;
  public String PrsnlRlt;
  public String PrsnlRltTyp;
  public String Cmmt;
  public String CustRsk;
  public String ACHPymt;
  public String OrigACHPymt;
  public String InfoObtnBy;
  public String CmpltDte;
  public String UsrDefFld1;
  public String UsrDefFld2;
  public String UsrDefFld3;
  public String UsrDefFld4;
  public String UsrDefFld5;
  public String UsrDefFld6;
  public String UsrDefFld7;
  public String UsrDefFld8;
  public String UsrDefFld9;
  public String UsrDefFld10;
  public String UsrDefFld11;
  public String UsrDefFld12;
  public String UsrDefFld13;
  public String UsrDefFld14;
  public String UsrDefFld15;
  public String UsrDefFld16;
  public String UsrDefFld17;
  public String UsrDefFld18;
  public String UsrDefFld19;
  public String UsrDefFld20;
  public String UsrDefFld21;
  public String UsrDefFld22;
  public String UsrDefFld23;
  public String UsrDefFld24;
  public String UsrDefFld25;
  public String UsrDefFld26;
  public String UsrDefFld27;
  public String UsrDefFld28;
  public String UsrDefFld29;
  public String UsrDefFld30;
  public String UsrDefFld31;
  public String UsrDefFld32;
  public String UsrDefFld33;
  public String UsrDefFld34;
  public String UsrDefFld35;
  public String UsrDefFld36;
  public String UsrDefFld37;
  public String UsrDefFld38;
  public String UsrDefFld39;
  public String UsrDefFld40;
  public String CntryCtznshp;
  public String CntryDualCtznshp;
  public String RsdntPrsn;
  public String ScndyEmplr;
  public String OccpnDesc;
  public String Title;
  public String FullTime;
  public String DescBus;
  public String HighRisk;
  public String MnySrvBus;
  public String MnyOrdr;
  public String MnyOrdrReg;
  public String MnyOrdrCnfmID;
  public String MnyOrdrActAgnt;
  public String MnyOrdrMaxDailyAmt;
  public String MnyOrdrMthlySales;
  public String MnyOrdrPrcntIncm;
  public String TrvlrCk;
  public String TrvlrCkReg;
  public String TrvlrCkCnfrmID;
  public String TrvlrCkActAgnt;
  public String TrvlrCkMaxAmt;
  public String TrvlrCkMthlySales;
  public String TrvlrCkPrcntIncome;
  public String MnyTrn;
  public String MnyTxnReg;
  public String MnyTrnRegConfrmID;
  public String MnyTrnActAgnt;
  public String MnyTrnMaxDailyAmt;
  public String MnyTrnMthlySales;
  public String MnyTrnPrcntIncome;
  public String CkCash;
  public String CkCashReg;
  public String CkCashRegCnfrmID;
  public String CkCashActAgnt;
  public String CkCashMaxAmt;
  public String CkCashMthlySales;
  public String CkCashPrcntIncome;
  public String CrncyExchg;
  public String CrncyExchgReg;
  public String CrncyExchgCnfmID;
  public String CrncyExchgActAgnt;
  public String CrncyExchgMaxAmt;
  public String CrncyExchgMthlySale;
  public String CrncyExchgPrcntIncome;
  public String CrncyDeal;
  public String CrncyDealReg;
  public String CrncyDealRegCnfmID;
  public String CrncyDealActAgnt;
  public String CrncyDealMaxAmt;
  public String CrncyDealMthlySales;
  public String CrncyDealPrcntIncome;
  public String StrVal;
  public String StrValReg;
  public String StrValRegCnfmID;
  public String StrValActAgnt;
  public String StrValMaxAmt;
  public String StrValMthlySale;
  public String StrValPrcntIncome;
 

  public void setValue(String fieldname, String fieldValue) {
    switch on fieldname {
      when 'CustNbr' {
        CustNbr = fieldValue;
      }
      when 'InitDp' {
        InitDp = fieldValue;
      }
      when 'TypOfFunds' {
        TypOfFunds = fieldValue;
      }
      when 'SrcOfFunds' {
        SrcOfFunds = fieldValue;
      }
      when 'NbrOfDp' {
        NbrOfDp = fieldValue;
      }
      when 'TotDpAmt' {
        TotDpAmt = fieldValue;
      }
      when 'NbrCashDp' {
        NbrCashDp = fieldValue;
      }
      when 'CashDpAmt' {
        CashDpAmt = fieldValue;
      }
      when 'NbrOfCashWthdrwl' {
        NbrOfCashWthdrwl = fieldValue;
      }
      when 'CashWthdrwlAmt' {
        CashWthdrwlAmt = fieldValue;
      }
      when 'NbrOfChkWritn' {
        NbrOfChkWritn = fieldValue;
      }
      when 'CkAmtWritn' {
        CkAmtWritn = fieldValue;
      }
      when 'AntWireAct' {
        AntWireAct = fieldValue;
      }
      when 'DomInWireAct' {
        DomInWireAct = fieldValue;
      }
      when 'NbrDomWire' {
        NbrDomWire = fieldValue;
      }
      when 'DomInWireAmt' {
        DomInWireAmt = fieldValue;
      }
      when 'DomOutWireAct' {
        DomOutWireAct = fieldValue;
      }
      when 'NbrDomOutWire' {
        NbrDomOutWire = fieldValue;
      }
      when 'DomOutWireAmt' {
        DomOutWireAmt = fieldValue;
      }
      when 'FrgnInWireAct' {
        FrgnInWireAct = fieldValue;
      }
      when 'NbrFrgnInWire' {
        NbrFrgnInWire = fieldValue;
      }
      when 'FrgnInWireAmt' {
        FrgnInWireAmt = fieldValue;
      }
      when 'FrgnOutWireAct' {
        FrgnOutWireAct = fieldValue;
      }
      when 'NbrFrgnOutWire' {
        NbrFrgnOutWire = fieldValue;
      }
      when 'FrgnOutWireAmt' {
        FrgnOutWireAmt = fieldValue;
      }
      when 'PolExpsedOrg' {
        PolExpsedOrg = fieldValue;
      }
      when 'PolRel' {
        PolRel = fieldValue;
      }
      when 'PrsnlRlt' {
        PrsnlRlt = fieldValue;
      }
      when 'PrsnlRltTyp' {
        PrsnlRltTyp = fieldValue;
      }
      when 'Cmmt' {
        Cmmt = fieldValue;
      }
      when 'CustRsk' {
        CustRsk = fieldValue;
      }
      when 'ACHPymt' {
        ACHPymt = fieldValue;
      }
      when 'OrigACHPymt' {
        OrigACHPymt = fieldValue;
      }
      when 'InfoObtnBy' {
        InfoObtnBy = fieldValue;
      }
      when 'CmpltDte' {
        CmpltDte = fieldValue;
      }
      when 'UsrDefFld1' {
        UsrDefFld1 = fieldValue;
      }
      when 'UsrDefFld2' {
        UsrDefFld2 = fieldValue;
      }
      when 'UsrDefFld3' {
        UsrDefFld3 = fieldValue;
      }
      when 'UsrDefFld4' {
        UsrDefFld4 = fieldValue;
      }
      when 'UsrDefFld5' {
        UsrDefFld5 = fieldValue;
      }
      when 'UsrDefFld6' {
        UsrDefFld6 = fieldValue;
      }
      when 'UsrDefFld7' {
        UsrDefFld7 = fieldValue;
      }
      when 'UsrDefFld8' {
        UsrDefFld8 = fieldValue;
      }
      when 'UsrDefFld9' {
        UsrDefFld9 = fieldValue;
      }
      when 'UsrDefFld10' {
        UsrDefFld10 = fieldValue;
      }
      when 'UsrDefFld11' {
        UsrDefFld11 = fieldValue;
      }
      when 'UsrDefFld12' {
        UsrDefFld12 = fieldValue;
      }
      when 'UsrDefFld13' {
        UsrDefFld13 = fieldValue;
      }
      when 'UsrDefFld14' {
        UsrDefFld14 = fieldValue;
      }
      when 'UsrDefFld15' {
        UsrDefFld15 = fieldValue;
      }
      when 'UsrDefFld16' {
        UsrDefFld16 = fieldValue;
      }
      when 'UsrDefFld17' {
        UsrDefFld17 = fieldValue;
      }
      when 'UsrDefFld18' {
        UsrDefFld18 = fieldValue;
      }
      when 'UsrDefFld19' {
        UsrDefFld19 = fieldValue;
      }
      when 'UsrDefFld20' {
        UsrDefFld20 = fieldValue;
      }
      when 'UsrDefFld21' {
        UsrDefFld21 = fieldValue;
      }
      when 'UsrDefFld22' {
        UsrDefFld22 = fieldValue;
      }
      when 'UsrDefFld23' {
        UsrDefFld23 = fieldValue;
      }
      when 'UsrDefFld24' {
        UsrDefFld24 = fieldValue;
      }
      when 'UsrDefFld25' {
        UsrDefFld25 = fieldValue;
      }
      when 'UsrDefFld26' {
        UsrDefFld26 = fieldValue;
      }
      when 'UsrDefFld27' {
        UsrDefFld27 = fieldValue;
      }
      when 'UsrDefFld28' {
        UsrDefFld28 = fieldValue;
      }
      when 'UsrDefFld29' {
        UsrDefFld29 = fieldValue;
      }
      when 'UsrDefFld30' {
        UsrDefFld30 = fieldValue;
      }
      when 'UsrDefFld31' {
        UsrDefFld31 = fieldValue;
      }
      when 'UsrDefFld32' {
        UsrDefFld32 = fieldValue;
      }
      when 'UsrDefFld33' {
        UsrDefFld33 = fieldValue;
      }
      when 'UsrDefFld34' {
        UsrDefFld34 = fieldValue;
      }
      when 'UsrDefFld35' {
        UsrDefFld35 = fieldValue;
      }
      when 'UsrDefFld36' {
        UsrDefFld36 = fieldValue;
      }
      when 'UsrDefFld37' {
        UsrDefFld37 = fieldValue;
      }
      when 'UsrDefFld38' {
        UsrDefFld38 = fieldValue;
      }
      when 'UsrDefFld39' {
        UsrDefFld39 = fieldValue;
      }
      when 'UsrDefFld40' {
        UsrDefFld40 = fieldValue;
      }
      when 'CntryCtznshp' {
        CntryCtznshp = fieldValue;
      }
      when 'CntryDualCtznshp' {
        CntryDualCtznshp = fieldValue;
      }
      when 'RsdntPrsn' {
        RsdntPrsn = fieldValue;
      }
      when 'ScndyEmplr' {
        ScndyEmplr = fieldValue;
      }
      when 'OccpnDesc' {
        OccpnDesc = fieldValue;
      }
      when 'Title' {
        Title = fieldValue;
      }
      when 'FullTime' {
        FullTime = fieldValue;
      }
      when 'DescBus' {
        DescBus = fieldValue;
      }
      when 'HighRisk' {
        HighRisk = fieldValue;
      }
      when 'MnySrvBus' {
        MnySrvBus = fieldValue;
      }
      when 'MnyOrdr' {
        MnyOrdr = fieldValue;
      }
      when 'MnyOrdrReg' {
        MnyOrdrReg = fieldValue;
      }
      when 'MnyOrdrCnfmID' {
        MnyOrdrCnfmID = fieldValue;
      }
      when 'MnyOrdrActAgnt' {
        MnyOrdrActAgnt = fieldValue;
      }
      when 'MnyOrdrMaxDailyAmt' {
        MnyOrdrMaxDailyAmt = fieldValue;
      }
      when 'MnyOrdrMthlySales' {
        MnyOrdrMthlySales = fieldValue;
      }
      when 'MnyOrdrPrcntIncm' {
        MnyOrdrPrcntIncm = fieldValue;
      }
      when 'TrvlrCk' {
        TrvlrCk = fieldValue;
      }
      when 'TrvlrCkReg' {
        TrvlrCkReg = fieldValue;
      }
      when 'TrvlrCkCnfrmID' {
        TrvlrCkCnfrmID = fieldValue;
      }
      when 'TrvlrCkActAgnt' {
        TrvlrCkActAgnt = fieldValue;
      }
      when 'TrvlrCkMaxAmt' {
        TrvlrCkMaxAmt = fieldValue;
      }
      when 'TrvlrCkMthlySales' {
        TrvlrCkMthlySales = fieldValue;
      }
      when 'TrvlrCkPrcntIncome' {
        TrvlrCkPrcntIncome = fieldValue;
      }
      when 'MnyTrn' {
        MnyTrn = fieldValue;
      }
      when 'MnyTxnReg' {
        MnyTxnReg = fieldValue;
      }
      when 'MnyTrnRegConfrmID' {
        MnyTrnRegConfrmID = fieldValue;
      }
      when 'MnyTrnActAgnt' {
        MnyTrnActAgnt = fieldValue;
      }
      when 'MnyTrnMaxDailyAmt' {
        MnyTrnMaxDailyAmt = fieldValue;
      }
      when 'MnyTrnMthlySales' {
        MnyTrnMthlySales = fieldValue;
      }
      when 'MnyTrnPrcntIncome' {
        MnyTrnPrcntIncome = fieldValue;
      }
      when 'CkCash' {
        CkCash = fieldValue;
      }
      when 'CkCashReg' {
        CkCashReg = fieldValue;
      }
      when 'CkCashRegCnfrmID' {
        CkCashRegCnfrmID = fieldValue;
      }
      when 'CkCashActAgnt' {
        CkCashActAgnt = fieldValue;
      }
      when 'CkCashMaxAmt' {
        CkCashMaxAmt = fieldValue;
      }
      when 'CkCashMthlySales' {
        CkCashMthlySales = fieldValue;
      }
      when 'CkCashPrcntIncome' {
        CkCashPrcntIncome = fieldValue;
      }
      when 'CrncyExchg' {
        CrncyExchg = fieldValue;
      }
      when 'CrncyExchgReg' {
        CrncyExchgReg = fieldValue;
      }
      when 'CrncyExchgCnfmID' {
        CrncyExchgCnfmID = fieldValue;
      }
      when 'CrncyExchgActAgnt' {
        CrncyExchgActAgnt = fieldValue;
      }
      when 'CrncyExchgMaxAmt' {
        CrncyExchgMaxAmt = fieldValue;
      }
      when 'CrncyExchgMthlySale' {
        CrncyExchgMthlySale = fieldValue;
      }
      when 'CrncyExchgPrcntIncome' {
        CrncyExchgPrcntIncome = fieldValue;
      }
      when 'CrncyDeal' {
        CrncyDeal = fieldValue;
      }
      when 'CrncyDealReg' {
        CrncyDealReg = fieldValue;
      }
      when 'CrncyDealRegCnfmID' {
        CrncyDealRegCnfmID = fieldValue;
      }
      when 'CrncyDealActAgnt' {
        CrncyDealActAgnt = fieldValue;
      }
      when 'CrncyDealMaxAmt' {
        CrncyDealMaxAmt = fieldValue;
      }
      when 'CrncyDealMthlySales' {
        CrncyDealMthlySales = fieldValue;
      }
      when 'CrncyDealPrcntIncome' {
        CrncyDealPrcntIncome = fieldValue;
      }
      when 'StrVal' {
        StrVal = fieldValue;
      }
      when 'StrValReg' {
        StrValReg = fieldValue;
      }
      when 'StrValRegCnfmID' {
        StrValRegCnfmID = fieldValue;
      }
      when 'StrValActAgnt' {
        StrValActAgnt = fieldValue;
      }
      when 'StrValMaxAmt' {
        StrValMaxAmt = fieldValue;
      }
      when 'StrValMthlySale' {
        StrValMthlySale = fieldValue;
      }
      when 'StrValPrcntIncome' {
        StrValPrcntIncome = fieldValue;
      }
    }
  }
}