public class HTTPCalloutConstants {
  public static String CONTENT_TYPE = 'content-type';
  public static String APPLICATION_JSON = 'application/json';
  public static String ACCEPT_HEADER = 'Accept';
  public static String HTTP_METHOD_POST = 'POST';
  public static String HTTP_METHOD_PUT = 'PUT';
  public static Integer DEFAULT_TIMEOUT = 120000;
  public static String AUTHORIZATION_HEADER = 'Authorization';
  public static String JWT = 'JWT ';
  public static String HTTP_METHOD_GET = 'GET';
  public static Integer HTTP_STATUS_OK = 200;
  public static Integer HTTP_STATUS_CREATED = 201;
  public static String APP_ID_CUSTOMER = 'CI';
  public static String APP_ID_DEPOSIT_ORIGINATION = 'DO';
  public static String APP_ID_DEPOSIT = 'DP';
  public static String APP_ID_FUND_MANAGEMENT = 'FM';
}