ID,NAME,TFFA__AUTHORITY__C,TFFA__CATEGORY__C,TFFA__CODE__C,TFFA__DESCRIPTION__C,TFFA__DISABLED__C,TFFA__LABEL__C
56001,Agent,,OTHER,AGENT,A party than can perform certain action on behalf of the owner.,FALSE,Agent
56002,Authorized Signatory,,SIGNER,AUTHORIZED_SIGNATORY,A party who has been authorized to sign documents. Also called a signing officer.,FALSE,Authorized Signatory
56003,Borrower,,OWNER,BORROWER,"A party that takes out a loan from a bank under an agreement to pay it back later, typically with interest.",FALSE,Borrower
56004,Co-Borrower,,OWNER,CO_BORROWER,"An additional borrower who, along with the primary borrower, accepts responsibility for repaying the debt",FALSE,Co-Borrower
56005,Co-Signer,,SIGNER,CO_SIGNER,A party who signs the account documents together with the other party (account owner).,FALSE,Co-Signer
56006,Contributor,,OTHER,CONTRIBUTOR,A party who deposits money on behalf of the owner (typically a minor).,FALSE,Contributor
56007,DBA,,OTHER,DBA,"When the owners of a firm operate under a business name (fictitious) different from their registered, legal name.",FALSE,DBA
56008,Guarantor,,OTHER,GUARANTOR,A party that endorses a three party agreement to guarantee that promises made by the first party (account owner) to the second party (bank) will be fulfilled.,FALSE,Guarantor
56009,Joint Owner,,OWNER,JOINT_OWNER,Used when two or more parties own the account.,FALSE,Joint Owner
56010,Owner,,OWNER,OWNER,Owner of the account,FALSE,Owner
56011,Real Estate Agent,,AGENT,REALTOR,A party who acts as an agent for the sale and purchase of buildings and land. An estate agent.,FALSE,Real Estate Agent
56012,Builder,,AGENT,BUILDER,A party who acts as a manufactturer for the buildings and land.,FALSE,Builder
56013,Listing Agent,,AGENT,LISTING_AGENT,A party who acts as an agent to list for the sale and purchase of buildings and land.,FALSE,Listing Agent
56014,Property Owner,,AGENT,PROPERTY_OWNER,Individual or legal entity with legal title to a property.,FALSE,Property Owner
56015,Referral Source,,AGENT,REFERRAL_SOURCE,A party who has referred for the sale and purchase of buildings and land.,FALSE,Referral Source
56016,Seller,,AGENT,PROPERTY_SELLER,A party who acts as a seller of the buildings and land in the transaction.,FALSE,Seller
56017,Responsible Individual,,OTHER,RESPONSIBLE_INDIVIDUAL,The  responsible individual named by the contributor shall be a parent or guardian of the designated beneficiary.,FALSE,Responsible Individual
56018,Designated Beneficiary,,OTHER,DESIGNATED_BENEFICIARY,A minor who receives all the balance of the education savings account,FALSE,Designated Beneficiary (Student)
56019,Successor Responsible Individual,,OTHER,SUCCESSOR_RESPONSIBLE_INDIVIDUAL,A person named to succeed in case the responsible individual is incapacitated,FALSE,Successor Responsible Individual
