{
  "Party__c": [
    {
      "Name": "Kris Marrier",
      "Type__c": "INDIVIDUAL",
      "IDVStatus__c": "PASSED",
      "DebitBureauStatus__c": "PASSED",
      "ExternalId__c": "P-2001",
      "BirthDate__c": "1968-02-02",
      "Citizenship__c": "Citizen",
      "FirstName__c": "Kris",
      "IsExistingCustomer__c": true,
      "MonthlyPayment__c": "1000",
      "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
      "MaritalStatus__c": "Married",
      "LastName__c": "Marrier",
      "MiddleName__c": "",
      "NationalIdentifierType__c": "SSN",
      "NationalIdentifierValue__c": "343433343",
      "PrefillSource__c": "IDScan",
      "Prefilled__c": true,
      "PrimaryEmailType__c": "PRIMARY",
      "PrimaryEmail__c": "kris@mail.com",
      "PrimaryPhoneType__c": "HOME",
      "PrimaryPhone__c": "+19898989898",
      "SecondaryEmailType__c": "SECONDARY",
      "SecondaryPhoneType__c": "WORK",
      "OnboardingDate__c": "2000-03-01",
      "AddressXrefs__r": [
        {
          "Name": "HOME",
          "Preferred__c": true,
          "Prefilled__c": true,
          "PeriodInYears__c": 10,
          "PeriodInMonths__c": 0,
          "Type__c": "HOME",
          "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
          "MonthlyPayment__c": "1000",
          "Address__r": {
            "City__c": "MORAGA",
            "Country__c": "US",
            "Line1__c": "228 Runamuck Pl",
            "State__c": "CA",
            "ZipCode__c": "94556-0000"
          }
        }
      ],
      "Identifications__r": [
        {
          "ExpirationDate__c": "2049-01-01",
          "IdentificationNumber__c": "C6740952",
          "IssueDate__c": "2017-09-02",
          "IssuingCountry__c": "US",
          "IssuingState__c": "CA",
          "PrefillSource__c": "IDScan",
          "Prefilled__c": true,
          "Type__c": "DL"
        }
      ],
      "OLBEnrolled__c": true
    },
    {
      "Name": "Willard Marrier",
      "Type__c": "INDIVIDUAL",
      "IDVStatus__c": "PASSED",
      "DebitBureauStatus__c": "PASSED",
      "ExternalId__c": "P-002",
      "BirthDate__c": "1978-02-02",
      "Citizenship__c": "Citizen",
      "FirstName__c": "Willard",
      "IsExistingCustomer__c": true,
      "MonthlyPayment__c": "1000",
      "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
      "MaritalStatus__c": "Married",
      "LastName__c": "Marrier",
      "MiddleName__c": "",
      "NationalIdentifierType__c": "SSN",
      "NationalIdentifierValue__c": "343433323",
      "PrefillSource__c": "IDScan",
      "Prefilled__c": true,
      "PrimaryEmailType__c": "PRIMARY",
      "PrimaryEmail__c": "willard@mail.com",
      "PrimaryPhoneType__c": "HOME",
      "PrimaryPhone__c": "+19898289898",
      "SecondaryEmailType__c": "SECONDARY",
      "SecondaryPhoneType__c": "WORK",
      "OnboardingDate__c": "2008-01-02",
      "AddressXrefs__r": [
        {
          "Name": "HOME",
          "Preferred__c": true,
          "Prefilled__c": true,
          "PeriodInYears__c": 10,
          "PeriodInMonths__c": 0,
          "Type__c": "HOME",
          "MonthlyPayment__c": "1000",
          "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
          "Address__r": {
            "City__c": "MORAGA",
            "Country__c": "US",
            "Line1__c": "6 Greenleaf Ave",
            "State__c": "CA",
            "ZipCode__c": "94556-0000"
          }
        }
      ],
      "Identifications__r": [
        {
          "ExpirationDate__c": "2049-01-01",
          "IdentificationNumber__c": "C6740952",
          "IssueDate__c": "2017-09-02",
          "IssuingCountry__c": "US",
          "IssuingState__c": "CA",
          "PrefillSource__c": "IDScan",
          "Prefilled__c": true,
          "Type__c": "DL"
        }
      ],
      "OLBEnrolled__c": true
    },
    {
      "Name": "Rose Parker",
      "Type__c": "INDIVIDUAL",
      "IDVStatus__c": "PASSED",
      "DebitBureauStatus__c": "PASSED",
      "ExternalId__c": "P-003",
      "BirthDate__c": "1980-02-02",
      "Citizenship__c": "Citizen",
      "FirstName__c": "Rose",
      "IsExistingCustomer__c": true,
      "MonthlyPayment__c": "1000",
      "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
      "MaritalStatus__c": "Married",
      "LastName__c": "Parker",
      "MiddleName__c": "",
      "NationalIdentifierType__c": "SSN",
      "NationalIdentifierValue__c": "343433313",
      "PrefillSource__c": "IDScan",
      "Prefilled__c": true,
      "PrimaryEmailType__c": "PRIMARY",
      "PrimaryEmail__c": "rose@mail.com",
      "PrimaryPhoneType__c": "HOME",
      "PrimaryPhone__c": "+19898999898",
      "SecondaryEmailType__c": "SECONDARY",
      "SecondaryPhoneType__c": "WORK",
      "OnboardingDate__c": "2010-08-01",
      "AddressXrefs__r": [
        {
          "Name": "HOME",
          "Preferred__c": true,
          "Prefilled__c": true,
          "PeriodInYears__c": 10,
          "PeriodInMonths__c": 0,
          "Type__c": "HOME",
          "MonthlyPayment__c": "1000",
          "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
          "Address__r": {
            "City__c": "MORAGA",
            "Country__c": "US",
            "Line1__c": "6 Greenleaf Ave",
            "State__c": "CA",
            "ZipCode__c": "94556-0000"
          }
        }
      ],
      "Identifications__r": [
        {
          "ExpirationDate__c": "2049-01-01",
          "IdentificationNumber__c": "C6740952",
          "IssueDate__c": "2017-09-02",
          "IssuingCountry__c": "US",
          "IssuingState__c": "CA",
          "PrefillSource__c": "IDScan",
          "Prefilled__c": true,
          "Type__c": "DL"
        }
      ],
      "OLBEnrolled__c": true
    },
    {
      "Name": "Debbie Galagher",
      "Type__c": "INDIVIDUAL",
      "ExternalId__c": "P-001",
      "BirthDate__c": "1978-02-02",
      "Citizenship__c": "Citizen",
      "FirstName__c": "Debbie",
      "IsExistingCustomer__c": true,
      "MonthlyPayment__c": "1000",
      "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
      "MaritalStatus__c": "Married",
      "LastName__c": "Galagher",
      "NationalIdentifierType__c": "SSN",
      "NationalIdentifierValue__c": "343433313",
      "PrefillSource__c": "IDScan",
      "Prefilled__c": true,
      "PrimaryEmailType__c": "PRIMARY",
      "PrimaryEmail__c": "debbie@canore.com",
      "PrimaryPhoneType__c": "HOME",
      "PrimaryPhone__c": "+19898999898",
      "SecondaryEmailType__c": "SECONDARY",
      "SecondaryPhoneType__c": "WORK",
      "OnboardingDate__c": "2004-05-01",
      "AddressXrefs__r": [
        {
          "Name": "HOME",
          "Preferred__c": true,
          "Prefilled__c": true,
          "PeriodInYears__c": 10,
          "PeriodInMonths__c": 0,
          "Type__c": "HOME",
          "MonthlyPayment__c": "1000",
          "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
          "Address__r": {
            "City__c": "Oakland",
            "Country__c": "US",
            "Line1__c": "500 William St",
            "State__c": "CA",
            "ZipCode__c": "94612-0000"
          }
        }
      ],
      "Identifications__r": [
        {
          "ExpirationDate__c": "2049-01-01",
          "IdentificationNumber__c": "C6740952",
          "IssueDate__c": "2017-09-02",
          "IssuingCountry__c": "US",
          "IssuingState__c": "CA",
          "PrefillSource__c": "IDScan",
          "Prefilled__c": true,
          "Type__c": "DL"
        }
      ],
      "OLBEnrolled__c": true
    },
    {
      "Name": "Emily Galagher",
      "Type__c": "INDIVIDUAL",
      "ExternalId__c": "P-2002",
      "BirthDate__c": "2010-02-02",
      "Citizenship__c": "Citizen",
      "FirstName__c": "Emily",
      "IsExistingCustomer__c": true,
      "MonthlyPayment__c": "1000",
      "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
      "LastName__c": "Galagher",
      "NationalIdentifierType__c": "SSN",
      "NationalIdentifierValue__c": "343433332",
      "PrefillSource__c": "IDScan",
      "Prefilled__c": true,
      "PrimaryEmailType__c": "PRIMARY",
      "PrimaryEmail__c": "emily@canore.com",
      "PrimaryPhoneType__c": "HOME",
      "PrimaryPhone__c": "+19898999898",
      "SecondaryEmailType__c": "SECONDARY",
      "SecondaryPhoneType__c": "WORK",
      "AddressXrefs__r": [
        {
          "Name": "HOME",
          "Preferred__c": true,
          "Prefilled__c": true,
          "PeriodInYears__c": 10,
          "PeriodInMonths__c": 0,
          "Type__c": "HOME",
          "MonthlyPayment__c": "1000",
          "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
          "Address__r": {
            "City__c": "Oakland",
            "Country__c": "US",
            "Line1__c": "500 William St",
            "State__c": "CA",
            "ZipCode__c": "94612-0000"
          }
        }
      ],
      "Identifications__r": [
        {
          "ExpirationDate__c": "2049-01-01",
          "IdentificationNumber__c": "C6740952",
          "IssueDate__c": "2017-09-02",
          "IssuingCountry__c": "US",
          "IssuingState__c": "CA",
          "PrefillSource__c": "IDScan",
          "Prefilled__c": true,
          "Type__c": "DL"
        }
      ],
      "OLBEnrolled__c": true
    },
    {
      "Name": "Mila Saldonado",
      "Type__c": "INDIVIDUAL",
      "AgentDetails__r": [
        {
          "Skills__c": "LOAN_ORIGINATOR",
          "LoanOriginatorType__c": "LENDER",
          "OtherDescription__c": "Executive Loan Officer",
          "SkillAdditionalDescription__c": "Mortgage Lending Originator",
          "IdentifierValue__c": "150269",
          "User__r": {
            "Name": "Mila Saldonado"
          }
        }
      ],
      "AddressXrefs__r": [
        {
          "Type__c": "REGISTERED",
          "Address__r": {
            "Country__c": "US",
            "Line2__c": "Manhattan Manhattan",
            "Line1__c": "245 Park Avenue",
            "City__c": "New York",
            "State__c": "NY",
            "ZipCode__c": "10029",
            "GeoCoordinate__Latitude__s": 40.7547829,
            "GeoCoordinate__Longitude__s": -73.97524779999998
          }
        }
      ],
      "FirstName__c": "Mila",
      "LastName__c": "Saldonado",
      "PrimaryPhone__c": "+12133734253",
      "PrimaryEmail__c": "mila@mail.com"
    },
    {
      "Name": "Brenda Jacobs",
      "Type__c": "INDIVIDUAL",
      "AgentDetails__r": [
        {
          "Skills__c": "LOAN_ORIGINATOR",
          "LoanOriginatorType__c": "LENDER",
          "OtherDescription__c": "Executive Loan Officer",
          "SkillAdditionalDescription__c": "Mortgage Lending Originator",
          "IdentifierValue__c": "371149"
        }
      ],
      "AddressXrefs__r": [
        {
          "Type__c": "REGISTERED",
          "Address__r": {
            "Country__c": "US",
            "Line2__c": "Manhattan Manhattan",
            "Line1__c": "245 Park Avenue",
            "City__c": "New York",
            "State__c": "NY",
            "ZipCode__c": "10029",
            "GeoCoordinate__Latitude__s": 40.7547829,
            "GeoCoordinate__Longitude__s": -73.97524779999998
          }
        }
      ],
      "FirstName__c": "Brenda",
      "LastName__c": "Jacobs",
      "PrimaryPhone__c": "+12133734253",
      "PrimaryEmail__c": "brenda@mail.com"
    },
    {
      "Name": "Joan Burris",
      "Type__c": "INDIVIDUAL",
      "AgentDetails__r": [
        {
          "Skills__c": "LISTING_AGENT",
          "SkillAdditionalDescription__c": "Mortgage Listing Agent",
          "IdentifierValue__c": "XA-212234"
        }
      ],
      "AddressXrefs__r": [
        {
          "Type__c": "REGISTERED",
          "Address__r": {
            "Country__c": "US",
            "Line2__c": "Manhattan Manhattan",
            "Line1__c": "245 Park Avenue",
            "City__c": "New York",
            "State__c": "NY",
            "ZipCode__c": "10029",
            "GeoCoordinate__Latitude__s": 40.7547829,
            "GeoCoordinate__Longitude__s": -73.97524779999998
          }
        }
      ],
      "FirstName__c": "Joan",
      "LastName__c": "Burris",
      "PrimaryPhone__c": "+12133734253",
      "PrimaryEmail__c": "joan@mail.com"
    },
    {
      "Name": "Sam Walters",
      "Type__c": "INDIVIDUAL",
      "RelatedPartyXrefs__r": [
        {
          "Party__r": {
            "Type__c": "ORGANIZATION",
            "AgentDetails__r": [
              {
                "Skills__c": "BUILDER",
                "IdentifierValue__c": "XA-12323",
                "IdentifierIssuingState__c": "TX",
                "IdentifierIssuingAuthority__c": "TXNAHB",
                "IdentifierIssueDate__c": "2000-01-01",
                "IdentifierAuthorityType__c": "PUBLIC_STATE"
              }
            ],
            "AddressXrefs__r": [
              {
                "Type__c": "REGISTERED",
                "Address__r": {
                  "Country__c": "US",
                  "Line1__c": "2345 Sage Road",
                  "Line2__c": "Westside",
                  "City__c": "Houston",
                  "State__c": "TX",
                  "ZipCode__c": "77056",
                  "GeoCoordinate__Latitude__s": 29.7438952,
                  "GeoCoordinate__Longitude__s": -95.4661279
                }
              }
            ],
            "LegalName__c": "Emblem Spaces"
          },
          "RelationCodeValue__c": "PRIMARY_CONTACT",
          "RelationCategory__c": "BUSINESS",
          "Name": "Primary Contact"
        }
      ],
      "AgentDetails__r": [
        {
          "Skills__c": "BUILDER",
          "IdentifierValue__c": "XA-2344",
          "IdentifierIssuingState__c": "TX",
          "IdentifierIssuingAuthority__c": "TXNAHB",
          "IdentifierIssueDate__c": "2000-01-01",
          "IdentifierAuthorityType__c": "PUBLIC_STATE"
        }
      ],
      "FirstName__c": "Sam",
      "LastName__c": "Walters",
      "PrimaryPhone__c": "+12133734253",
      "PrimaryEmail__c": "sam@mail.com"
    },
    {
      "Name": "Val Johnson",
      "Type__c": "INDIVIDUAL",
      "IDVStatus__c": "PASSED",
      "DebitBureauStatus__c": "PASSED",
      "BirthDate__c": "1968-01-01",
      "Citizenship__c": "Citizen",
      "ExternalId__c": "P-2004",
      "FirstName__c": "Val",
      "IsExistingCustomer__c": true,
      "MonthlyPayment__c": "1000",
      "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
      "MaritalStatus__c": "Married",
      "LastName__c": "Johnson",
      "MiddleName__c": "",
      "NationalIdentifierType__c": "SSN",
      "NationalIdentifierValue__c": "121212121",
      "PrefillSource__c": "IDScan",
      "Prefilled__c": true,
      "PrimaryEmailType__c": "PRIMARY",
      "PrimaryEmail__c": "val@mail.com",
      "PrimaryPhoneType__c": "HOME",
      "PrimaryPhone__c": "+19898989898",
      "SecondaryEmailType__c": "SECONDARY",
      "SecondaryPhoneType__c": "WORK",
      "AddressXrefs__r": [
        {
          "Name": "HOME",
          "Preferred__c": true,
          "Prefilled__c": true,
          "PeriodInYears__c": 10,
          "PeriodInMonths__c": 0,
          "Type__c": "HOME",
          "MonthlyPayment__c": "1000",
          "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
          "Address__r": {
            "City__c": "MORAGA",
            "Country__c": "US",
            "Line1__c": "228 Runamuck Pl",
            "State__c": "CA",
            "ZipCode__c": "94556-0000"
          }
        }
      ],
      "Identifications__r": [
        {
          "ExpirationDate__c": "2049-01-01",
          "IdentificationNumber__c": "C6740952",
          "IssueDate__c": "2017-09-02",
          "IssuingCountry__c": "US",
          "IssuingState__c": "CA",
          "PrefillSource__c": "IDScan",
          "Prefilled__c": true,
          "Type__c": "DL"
        }
      ],
      "OLBEnrolled__c": true
    },
    {
      "Name": "Emily Johnson",
      "Type__c": "INDIVIDUAL",
      "IDVStatus__c": "PASSED",
      "DebitBureauStatus__c": "PASSED",
      "BirthDate__c": "1968-01-01",
      "Citizenship__c": "Citizen",
      "ExternalId__c": "P-2005",
      "FirstName__c": "Emily",
      "IsExistingCustomer__c": true,
      "MonthlyPayment__c": "1000",
      "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
      "MaritalStatus__c": "Married",
      "LastName__c": "Johnson",
      "MiddleName__c": "",
      "NationalIdentifierType__c": "SSN",
      "NationalIdentifierValue__c": "121212121",
      "PrefillSource__c": "IDScan",
      "Prefilled__c": true,
      "PrimaryEmailType__c": "PRIMARY",
      "PrimaryEmail__c": "emily@mail.com",
      "PrimaryPhoneType__c": "HOME",
      "PrimaryPhone__c": "+19898989898",
      "SecondaryEmailType__c": "SECONDARY",
      "SecondaryPhoneType__c": "WORK",
      "AddressXrefs__r": [
        {
          "Name": "HOME",
          "Preferred__c": true,
          "Prefilled__c": true,
          "PeriodInYears__c": 10,
          "PeriodInMonths__c": 0,
          "Type__c": "HOME",
          "MonthlyPayment__c": "1000",
          "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
          "Address__r": {
            "City__c": "MORAGA",
            "Country__c": "US",
            "Line1__c": "228 Runamuck Pl",
            "State__c": "CA",
            "ZipCode__c": "94556-0000"
          }
        }
      ],
      "Identifications__r": [
        {
          "ExpirationDate__c": "2049-01-01",
          "IdentificationNumber__c": "C6740952",
          "IssueDate__c": "2017-09-02",
          "IssuingCountry__c": "US",
          "IssuingState__c": "CA",
          "PrefillSource__c": "IDScan",
          "Prefilled__c": true,
          "Type__c": "DL"
        }
      ],
      "OLBEnrolled__c": true
    },
    {
      "Name": "Adam Johnson",
      "Type__c": "INDIVIDUAL",
      "IDVStatus__c": "PASSED",
      "DebitBureauStatus__c": "PASSED",
      "BirthDate__c": "1968-01-01",
      "Citizenship__c": "Citizen",
      "ExternalId__c": "P-2006",
      "FirstName__c": "Adam",
      "IsExistingCustomer__c": true,
      "MonthlyPayment__c": "1000",
      "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
      "MaritalStatus__c": "Married",
      "LastName__c": "Johnson",
      "MiddleName__c": "",
      "NationalIdentifierType__c": "SSN",
      "NationalIdentifierValue__c": "121212121",
      "PrefillSource__c": "IDScan",
      "Prefilled__c": true,
      "PrimaryEmailType__c": "PRIMARY",
      "PrimaryEmail__c": "adam@mail.com",
      "PrimaryPhoneType__c": "HOME",
      "PrimaryPhone__c": "+19898989898",
      "SecondaryEmailType__c": "SECONDARY",
      "SecondaryPhoneType__c": "WORK",
      "AddressXrefs__r": [
        {
          "Name": "HOME",
          "Preferred__c": true,
          "Prefilled__c": true,
          "PeriodInYears__c": 10,
          "PeriodInMonths__c": 0,
          "Type__c": "HOME",
          "MonthlyPayment__c": "1000",
          "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
          "Address__r": {
            "City__c": "MORAGA",
            "Country__c": "US",
            "Line1__c": "228 Runamuck Pl",
            "State__c": "CA",
            "ZipCode__c": "94556-0000"
          }
        }
      ],
      "Identifications__r": [
        {
          "ExpirationDate__c": "2049-01-01",
          "IdentificationNumber__c": "C6740952",
          "IssueDate__c": "2017-09-02",
          "IssuingCountry__c": "US",
          "IssuingState__c": "CA",
          "PrefillSource__c": "IDScan",
          "Prefilled__c": true,
          "Type__c": "DL"
        }
      ],
      "OLBEnrolled__c": true
    },
    {
      "Name": "Kim Johnson",
      "Type__c": "INDIVIDUAL",
      "IDVStatus__c": "PASSED",
      "DebitBureauStatus__c": "PASSED",
      "BirthDate__c": "1968-01-01",
      "Citizenship__c": "Citizen",
      "ExternalId__c": "P-2007",
      "FirstName__c": "Kim",
      "IsExistingCustomer__c": true,
      "MonthlyPayment__c": "1000",
      "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
      "MaritalStatus__c": "Married",
      "LastName__c": "Johnson",
      "MiddleName__c": "",
      "NationalIdentifierType__c": "SSN",
      "NationalIdentifierValue__c": "121212121",
      "PrefillSource__c": "IDScan",
      "Prefilled__c": true,
      "PrimaryEmailType__c": "PRIMARY",
      "PrimaryEmail__c": "kim@mail.com",
      "PrimaryPhoneType__c": "HOME",
      "PrimaryPhone__c": "+19898989898",
      "SecondaryEmailType__c": "SECONDARY",
      "SecondaryPhoneType__c": "WORK",
      "AddressXrefs__r": [
        {
          "Name": "HOME",
          "Preferred__c": true,
          "Prefilled__c": true,
          "PeriodInYears__c": 10,
          "PeriodInMonths__c": 0,
          "Type__c": "HOME",
          "MonthlyPayment__c": "1000",
          "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
          "Address__r": {
            "City__c": "MORAGA",
            "Country__c": "US",
            "Line1__c": "228 Runamuck Pl",
            "State__c": "CA",
            "ZipCode__c": "94556-0000"
          }
        }
      ],
      "Identifications__r": [
        {
          "ExpirationDate__c": "2049-01-01",
          "IdentificationNumber__c": "C6740952",
          "IssueDate__c": "2017-09-02",
          "IssuingCountry__c": "US",
          "IssuingState__c": "CA",
          "PrefillSource__c": "IDScan",
          "Prefilled__c": true,
          "Type__c": "DL"
        }
      ],
      "OLBEnrolled__c": true
    }
  ],
  "Recommendation__c": [
    {
      "Name": "Reco 1",
      "Party__r": {
        "Name": "Kris Marrier"
      },
      "Items__r": [
        {
          "Description__c": "32% of customers who applied for card also opened a saving account",
          "ProductCode__c": "SAVPT",
          "SortOrder__c": 0
        }
      ]
    },
    {
      "Name": "Reco 2",
      "Party__r": {
        "Name": "Kris Marrier"
      },
      "Items__r": [
        {
          "Description__c": "Get $25 bonus on deposit of $250",
          "PromotionCode__c": "BONUS25",
          "SortOrder__c": 0
        }
      ]
    },
    {
      "Name": "Reco 3",
      "Party__r": {
        "Name": "Willard Marrier"
      },
      "Items__r": [
        {
          "Description__c": "For higher rates of interest linked to the growing economy.",
          "ProductCode__c": "SMONM",
          "SortOrder__c": 0
        }
      ]
    },
    {
      "Name": "Reco 4",
      "Party__r": {
        "Name": "Rose Parker"
      },
      "Items__r": [
        {
          "Description__c": "Affordable funds when you need them.",
          "ProductCode__c": "PCLPLUS",
          "SortOrder__c": 0
        },
        {
          "Description__c": "For customers that have a fluctuating account balance.",
          "ProductCode__c": "PCCKPC",
          "SortOrder__c": 1
        }
      ]
    },
    {
      "Name": "Reco 5",
      "Party__r": {
        "Name": "Debbie Galagher"
      },
      "Items__r": [
        {
          "Description__c": "32% of customers who applied for card also opened a saving account",
          "ProductCode__c": "SAVPT",
          "SortOrder__c": 0
        }
      ]
    },
    {
      "Name": "Reco 6",
      "Party__r": {
        "Name": "Debbie Galagher"
      },
      "Items__r": [
        {
          "Description__c": "Has equity on home and low rates make it very practical",
          "ProductCode__c": "HLLOC",
          "SortOrder__c": 0
        }
      ]
    },
    {
      "Name": "Reco 7",
      "Party__r": {
        "Name": "Kris Marrier"
      },
      "Items__r": [
        {
          "Description__c": "Bundle of products for customers that keep a regular monthly balance above $1,500",
          "ProductCode__c": "BUNDLECHECKING",
          "SortOrder__c": 0
        }
      ]
    },
    {
      "Name": "Ben Smith",
      "Type__c": "INDIVIDUAL",
      "IDVStatus__c": "PASSED",
      "DebitBureauStatus__c": "PASSED",
      "ExternalId__c": "P-2003",
      "BirthDate__c": "1964-11-03",
      "Citizenship__c": "Citizen",
      "FirstName__c": "Ben",
      "IsExistingCustomer__c": true,
      "MonthlyPayment__c": "1000",
      "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
      "MaritalStatus__c": "Married",
      "LastName__c": "Smith",
      "MiddleName__c": "",
      "NationalIdentifierType__c": "SSN",
      "NationalIdentifierValue__c": "344675890",
      "PrefillSource__c": "IDScan",
      "Prefilled__c": true,
      "PrimaryEmailType__c": "PRIMARY",
      "PrimaryEmail__c": "bensmith@gmail.com",
      "PrimaryPhoneType__c": "HOME",
      "PrimaryPhone__c": "+19898989898",
      "SecondaryEmailType__c": "SECONDARY",
      "SecondaryPhoneType__c": "WORK",
      "AddressXrefs__r": [
        {
          "Name": "HOME",
          "Preferred__c": true,
          "Prefilled__c": true,
          "PeriodInYears__c": 10,
          "PeriodInMonths__c": 0,
          "Type__c": "HOME",
          "MonthlyPayment__c": "1000",
          "HousingStatus__c": "OWNED_FREE_AND_CLEAR",
          "Address__r": {
            "City__c": "Springfield",
            "Country__c": "US",
            "Line1__c": "744 Evergreen Terrace",
            "State__c": "OR",
            "ZipCode__c": "97403"
          }
        }
      ],
      "Identifications__r": [
        {
          "ExpirationDate__c": "2049-01-01",
          "IdentificationNumber__c": "C6740950",
          "IssueDate__c": "2017-09-02",
          "IssuingCountry__c": "US",
          "IssuingState__c": "CA",
          "PrefillSource__c": "IDScan",
          "Prefilled__c": true,
          "Type__c": "DL"
        }
      ]
    }
  ],
  "FinancialAccount__c": [
    {
      "Name": "Premier Checking",
      "AccountNumber__c": "16309173448542896",
      "AccountTitle__c": "Kris Marrier",
      "HeldAway__c": false,
      "MaskedAccountNumber__c": "2896",
      "NickName__c": "Premier Checking",
      "OpenDate__c": "2021-06-08",
      "ProductCode__c": "CKPC",
      "RoutingNumber__c": "129052082",
      "State__c": "Init",
      "Status__c": "OPEN",
      "Parties__r": [
        {
          "Name": "Kris Marrier",
          "Primary__c": true,
          "RoleCode__c": "OWNER",
          "Role__c": "OWNER",
          "SortOrder__c": 1,
          "Party__r": {
            "Name": "Kris Marrier"
          }
        }
      ]
    }
  ]
}
